app:
  baseUrl: ${BACKSTAGE_BASE_URL}

backend:
  baseUrl: ${BACKSTAGE_BASE_URL}

  listen: ':7007'

  cors:
    origin: ${BACKSTAGE_BASE_URL}
    methods:
      - GET
      - HEAD
      - PATCH
      - POST
      - PUT
      - DELETE
    credentials: true

  database:
    client: pg
    connection:
      host: ${POSTGRES_HOST}
      port: ${POSTGRES_PORT}
      user: ${POSTGRES_USER}
      password: ${POSTGRES_PASSWORD}
      database: ${POSTGRES_DATABASE}

auth:
  environment: production

  providers:
    github:
      production:
        clientId: ${AUTH_GITHUB_CLIENT_ID}
        clientSecret: ${AUTH_GITHUB_CLIENT_SECRET}

        signIn:
          resolvers:
            - resolver: userIdMatchingUserEntityAnnotation

catalog:
  locations:
    - type: file
      target: ./examples/platform-org.yaml
      rules:
        - allow:
            - User
            - Group

    - type: file
      target: ./examples/platform-catalog.yaml
      rules:
        - allow:
            - Domain
            - System
            - Component
            - API
            - Resource

    - type: file
      target: ./examples/template/template.yaml
      rules:
        - allow:
            - Template
