apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: olawale-platform-engineering-portal
  description: Internal Developer Platform showcasing Platform Engineering, Cloud Engineering and DevOps projects.
  annotations:
    github.com/project-slug: AZ1600/platform-engineering-backstage-portal

spec:
  type: website
  owner: olawale-azeez
  lifecycle: production
