apiVersion: backstage.io/v1alpha1
kind: Component

metadata:
  name: ${{ values.name }}
  title: ${{ values.name }}
  description: ${{ values.description | dump }}
  annotations:
    backstage.io/techdocs-ref: dir:.
  tags:
    - generated-service
    - ${{ values.runtime }}

spec:
  type: service
  lifecycle: experimental
  owner: ${{ values.owner }}
  system: internal-developer-platform