apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ai-resume-analyzer
  description: AI-powered resume analyzer using AWS Bedrock and Amazon Nova Pro.
  links:
    - url: https://github.com/AZ1600/ai-resume-analyzer-n8n
      title: GitHub Repository

spec:
  type: service
  lifecycle: production
  owner: olawale-azeez

---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: terraform-eks-platform
  description: Platform Engineering project provisioning AWS infrastructure and EKS with Terraform.

spec:
  type: service
  lifecycle: production
  owner: olawale-azeez

---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: gitops-argocd
  description: GitOps deployment platform using ArgoCD and Kubernetes.

spec:
  type: service
  lifecycle: production
  owner: olawale-azeez

---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: observability-platform
  description: Monitoring and observability stack using Prometheus and Grafana.

spec:
  type: service
  lifecycle: production
  owner: olawale-azeez

---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: pharmacy-serverless-platform
  description: Serverless pharmacy application built on AWS.

spec:
  type: service
  lifecycle: production
  owner: olawale-azeez
