---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: guest
spec:
  memberOf:
    - guests

---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: guests
  description: Default guest users

spec:
  type: team
  children: []

---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: platform-team
  description: AZ1600 Platform Engineering Team

spec:
  type: team

  profile:
    displayName: Platform Engineering
    email: platform@az1600.com

  children: []